### ISSUE TITLE
getMostEfficientAction(): Important Infos & ongoing TODO

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#14]
# TODO

- [ ] add a extended method with a neural network
- [x] add a separate class for cleaner code
- [x] add getMostEfficientAction()
- [x] add sigmoid()
- [x] implement new Logic into every part
- [x] add a more suitable Log Class

**Comment by manuel3108** [comment]
getMostEfficientAction() is not dealing with cards / unable to play cards

**Comment by EasyDevCpp** [comment]
That's not what getMostEfficientAction() is supposed to do... It is actually able to play cards itself but misses the second action, which should be handled by your Part. Additionally there is no way to identify the most efficient card type, because it basically takes the average amount of each action.

**Comment by EasyDevCpp** [comment]
# About getMostEfficientAction's Quality Parameter:

The quality parameter basically represents the inverted threshold of the sigmoid function. As higher the Quality value gets as less the function is used! 

Each Part can change the used quality parameter by simply using: **super.setQuality(double)**

Minimum Quality is 0.25, so to speak the highest threshold. (100%)
Maximum Quality is 1.25, so to speak the lowest threshold. (0%)

The in my opinion best Quality value is 0.65. It's also the default value.

**Comment by manuel3108** [comment]
Ok, I think, that 0.65 is definetly to high. Should be at 0.3/0.35 in my opinion else AI is never playing.

Also `super.setQuality(double)` will only be important in the neyt turn played by  the bot because of the implementation in the `Part`.

**Comment by EasyDevCpp** [comment]
Nope. I have to change the sigmoid Funktion which is originally supposed to work with smaller values...also super.setQuality is supposed to be placed in the constructor

**Comment by EasyDevCpp** [comment]
Closing it right now.
